version: '3'

services:
  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    # depends_on:
    #   - db

  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=<usr_id>
  #     - POSTGRES_PASSWORD=<passwd>
  #     - POSTGRES_DB=AlphaQ
